version: '3.8'
services:
  app:
    container_name: app
    build:
      dockerfile: docker/Dockerfile
      context: ../.
    restart: always
    ports:
      - 3000:3000
    volumes:
      - /var/app
